services:
  node:
    image: node:21-alpine3.17
    depends_on:
      - mongo
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: "yarn dev"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: always
    ports:
      - "3001:8081"

volumes:
  mongo-data: