name: "Deployment"
on:
  release:
    types:
      - created
env:
    FRONT_ARTIFACT: build-frontend #Name of front artifact
    PREPARED_FOLDER: gamerhub #Temp folder in server VPS
    DESTINATION_FOLDER: /var/gamerhub #Folder where app is in server VPS
    FRONTEND_URL: https://gamerhub.fr
    BACKEND_URL: https://api.gamerhub.fr
    FALLBACK_LOCALE: en
    LOCALE: fr
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker-compose -f "./docker-compose.prod.yml" up -d 