name: Pull Request
on:
  pull_request:
    branches: [ develop ]
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: gamerhub-api:latest
          outputs: type=docker,dest=/tmp/gamerhub-api.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gamerhub-api
          path: /tmp/gamerhub-api.tar