name: "Create Release"
permissions:
  contents: write
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
    
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: gamerhub-api:latest
          outputs: type=docker,dest=/tmp/gamerhub-api.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gamerhub-api
          path: /tmp/gamerhub-api.tar